Feature(Analytics): Actionable Analytics
andela/theoden-rc pull request #15
Opened 2017-11-03 16:59 UTC by oahray

- Create a new plugin acccessible from the admin dashboard that routes to an analytics page
- Add meteor packages Highcharts, mrt:moment and Pikaday
- Add data visualization via charts
[Finishes #151980458]

#### What does this PR do?
GIVEN I am an admin,
WHEN I am on the Admin dashboard
THEN I should see a link that when clicked takes me to the Analytics page

GIVEN I am an admin
WHEN I am on the Analytics page
THEN I should be able to derive the following:
- A tabulated summary of Total Sales, Orders (total made, and total cancelled)
- Charts showing Sales and Orders dynamics
- Most profitable products (based on turnover)
- Most popular products (based on quantity sold)
- Product Comparison

#### Description of Task to be completed?
- Create a new plugin acccessible from the admin dashboard that routes to an analytics page
- Add meteor packages Highcharts, mrt:moment and Pikaday
- Add data visualization via charts

#### How should this be manually tested?
Log in as Admin and navigate to the statistics page from the admin dashboard. You should see tabular and graphical statistics of sales, orders, and products.

#### Any background context you want to provide?
A more visual format for data allows the admin to have a more quick and detailed guide to analytics regarding the shop and products. This method of data presentation will add more value by driving decisions made by the admin on future business related decisions.

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/151980458

#### Screenshots (if appropriate)
<img width="1432" alt="screen shot 2017-11-03 at 4 50 17 pm" src="https://user-images.githubusercontent.com/20444781/32386177-a432e290-c0c0-11e7-9298-dc4dfd9515af.png">
<img width="1369" alt="screen shot 2017-11-03 at 4 51 23 pm" src="https://user-images.githubusercontent.com/20444781/32386187-ae1c575a-c0c0-11e7-95c6-d8bf4fe46a1d.png">

2017-11-07 10:40 UTC, femisenjobi requested changes
- I think we can use a better design where the date filter is not `orphaned` on the page. DM'ed you some ideas
- Thanks for putting the table in a container. It's good to make use of some whitespace in your design.
- getAnalytics seemed too bulky for a single function
- added a comment for the redundant calculation, just put the final answer

2017-11-07 10:40 UTC, femisenjobi commented on imports/plugins/included/actionableAnalytics/client/templates/actionableAnalytics.js
> +  const oneDay = 1000 * 60 * 60 * 24;
No need to do this calculation here, especially since you already commented. Just put the final value

2017-11-07 11:37 UTC, oahray commented on imports/plugins/included/actionableAnalytics/client/templates/actionableAnalytics.js
> +  const oneDay = 1000 * 60 * 60 * 24;
Thanks. Fixed.

2017-11-08 11:05 UTC, femisenjobi approved these changes

2017-11-08 11:05 UTC, merged