#151980454 implement sorting and filtering
andela/theoden-rc pull request #24
Opened 2017-11-09 16:38 UTC by aimeedyki

#### What does this PR do?

Allows a user to filter and sort product search results by certain Price, date and vendor.

####Description of Task to be completed?

- filter search results by price range
- filter search result by vendor
- sort search result by date and price

#### How should this be manually tested?

- Click on the search icon
- Search for a product
- select a filter or sort criteria

#### Any background context you want to provide?

search results could not be filtered to further refine a search

#### What are the relevant pivotal tracker stories?

[https://www.pivotaltracker.com/story/show/151980454](https://www.pivotaltracker.com/story/show/151980454)

#### Screenshots (if appropriate)
<img width="1440" alt="screen shot 2017-11-09 at 5 32 39 pm" src="https://user-images.githubusercontent.com/28511567/32617015-27203e52-c574-11e7-9763-5f13502cd48d.png">
<img width="1440" alt="screen shot 2017-11-09 at 5 33 32 pm" src="https://user-images.githubusercontent.com/28511567/32617052-4106cf52-c574-11e7-985a-354488495f66.png">

2017-11-10 10:52 UTC, fidelisojeah commented
- A little overlap here
![screen shot 2017-11-10 at 11 36 56 am](https://user-images.githubusercontent.com/11561738/32655317-5db2e1e2-c60d-11e7-8e3c-bf22427494d3.png)

- Not sure this sort/filter panel is useful when admin is searching Accounts or Orders
![screen shot 2017-11-10 at 11 49 33 am](https://user-images.githubusercontent.com/11561738/32655367-90d03516-c60d-11e7-819d-85ea138d94cf.png)
![screen shot 2017-11-10 at 11 44 04 am](https://user-images.githubusercontent.com/11561738/32655368-90fa292a-c60d-11e7-929f-fa6286b7b25e.png)

2017-11-14 10:56 UTC, femisenjobi requested changes
Thanks for making the changes, I have 2 comments
- the conditional that returns the products seem restricting. Once my minimum filter is above the minimum price, the product is not included. If that happens and the max price is still below my max query, the product should still be suggested. I suggested a better conditional that solves that edge case
- Secondly, it would be great to use `type="number"` for the inputs. At the moment, it takes text and does not respond to arrow up/down buttons. Using `type="number"` gives us that feature and validation

2017-11-14 10:56 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +        if (minPrice >= queryMinPrice && maxPrice <= queryMaxPrice) {
Try this instead
```
if ((minPrice >= queryMinPrice && minPrice <= queryMaxPrice) || (maxPrice >= queryMinPrice && maxPrice <= queryMaxPrice)) {
...
}
```

2017-11-14 10:56 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/productSearch/productSort.html
> +        <input class="col-md-2" id="price-filter1" type="text" value="{{sliderMin}}"/>
Use `type="number"`

2017-11-14 10:56 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/productSearch/productSort.html
> +        <input class="col-md-2" id="price-filter2" type="text" value="{{sliderMax}}"/>
Use `type="number"` here too

2017-11-14 11:11 UTC, femisenjobi requested changes
Also, use
- col-xs-2 instead of col-md-2 (for the input fields)
- col-xs-7 instead of col-md-7 (for the slider)
This makes the input and slider appear on the same row even in mobile devices (md for laptops; sm for tabs; xs for phones)

2017-11-14 11:11 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/productSearch/productSort.html
> +        <input class="col-md-2" id="price-filter1" type="text" value="{{sliderMin}}"/>
also use `class="col-xs-2"` instead

2017-11-14 11:11 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/productSearch/productSort.html
> +        <div class="col-md-7 slider-fix" id="slider"></div>
Also, use class="col-xs-7" instead

2017-11-14 11:11 UTC, andela-fsenjobi commented on imports/plugins/included/ui-search/client/templates/productSearch/productSort.html
> +        <input class="col-md-2" id="price-filter2" type="text" value="{{sliderMax}}"/>
Also, use class="col-xs-2" instead

2017-11-14 11:33 UTC, aimeedyki commented
Thanks, changes have been implemented.

2017-11-14 14:45 UTC, femisenjobi approved these changes

2017-11-14 14:45 UTC, merged